# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.7
loader_version=0.17.2
parchment_version=1.21.7:2025.07.18

# Mod Properties
mod_version=21.6.0
maven_group=net.jmb19905
archives_base_name=niftycarts

# Dependencies
fabric_version=0.129.0+1.21.7
forgeconfigapiport_version=21.7.0
sodium_version=mc1.21.6-0.6.13-fabric